"""
@author = magnus.ersdal@uib.no
"""

# Imports
import os
import argparse
from generateScrubbingFile import Scrub
from ecc_functions import make_ecc_file
from makeparameters import make_parameter_file_and_ecc

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('filename', metavar='bitfile', type=str,
                    help='Filename of Xilinx bit-file generated by Vivado')
parser.add_argument('--verbose', action='store_true',
                    help='Verbose output')
args = parser.parse_args()
verbose = args.verbose
realpath = os.path.realpath(args.filename)
path, fn = os.path.split(realpath)
# Load configuration

cfgkeys = {'inFileName': realpath,
           'paramfname': os.path.join(path, "paramfile_" + fn),
           'fnEnding': '_ecc.bit',
           'bsEnding': '_bs.bit',
           'bsfile': "need_to_fill"
           }


def do():
    if verbose:
        print("Configuration:")
        print(cfgkeys)
    # Make blind scrubbing file
    s = Scrub()
    name = s.generate_scrubbing_file(cfgkeys['inFileName'], cfgkeys['bsEnding'], verbose=verbose)
    cfgkeys['bsfile'] = name

    # Make Page file
    make_parameter_file_and_ecc(cfgkeys['paramfname'], 0x100, 0x200, 0x300, verbose=verbose)

    # Make ECC bit-and blind-scrubbing -file
    make_ecc_file(cfgkeys['inFileName'], cfgkeys['fnEnding'], verbose=verbose)
    #
    make_ecc_file(cfgkeys['bsfile'], cfgkeys['fnEnding'], verbose=verbose)


if __name__ == '__main__':
    do()
